### ISSUE TITLE
Redis 5.x Deprecations

### ISSUE THREAD

**Issue by yachub** [puppetlabs/vmpooler#547]
I noticed at least a couple places in the logs of newer redis versions with deprecations:

```
Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /usr/local/bundle/gems/vmpooler-2.4.0/lib/vmpooler/pool_manager.rb:166:in `block in move_pending_vm_to_ready')
```
```
Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /usr/local/bundle/gems/vmpooler-2.4.0/lib/vmpooler/pool_manager.rb:425:in `block in _clone_vm')
```

**Comment by yachub** [comment]
Moving to Jira at https://puppet.atlassian.net/browse/POOLER-216

**Comment by yachub** [comment]
Duplicate issue opened, so added maintenance label to exclude.
